# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.route_shard_request import RouteShardRequest

class TestRouteShardRequest(unittest.TestCase):
    """RouteShardRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RouteShardRequest:
        """Test RouteShardRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RouteShardRequest`
        """
        model = RouteShardRequest()
        if include_optional:
            return RouteShardRequest(
                key = 'user_123',
                strategy = 'hash_based',
                for_read = False
            )
        else:
            return RouteShardRequest(
                key = 'user_123',
        )
        """

    def testRouteShardRequest(self):
        """Test RouteShardRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
