# coding: utf-8

"""
    TeachLink API

    TeachLink Backend API Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.courses_post_request import CoursesPostRequest

class TestCoursesPostRequest(unittest.TestCase):
    """CoursesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoursesPostRequest:
        """Test CoursesPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoursesPostRequest`
        """
        model = CoursesPostRequest()
        if include_optional:
            return CoursesPostRequest(
                title = '',
                description = ''
            )
        else:
            return CoursesPostRequest(
                title = '',
        )
        """

    def testCoursesPostRequest(self):
        """Test CoursesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
