# coding: utf-8

"""
    TeachLink API

    TeachLink Backend API Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.auth_login_post_request import AuthLoginPostRequest

class TestAuthLoginPostRequest(unittest.TestCase):
    """AuthLoginPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthLoginPostRequest:
        """Test AuthLoginPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthLoginPostRequest`
        """
        model = AuthLoginPostRequest()
        if include_optional:
            return AuthLoginPostRequest(
                email = '',
                password = ''
            )
        else:
            return AuthLoginPostRequest(
                email = '',
                password = '',
        )
        """

    def testAuthLoginPostRequest(self):
        """Test AuthLoginPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
