# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.payments_api import PaymentsApi


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_payment_intent(self) -> None:
        """Test case for create_payment_intent

        Create a payment intent
        """
        pass


if __name__ == '__main__':
    unittest.main()
