# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.upsert_reward_request import UpsertRewardRequest

class TestUpsertRewardRequest(unittest.TestCase):
    """UpsertRewardRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertRewardRequest:
        """Test UpsertRewardRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertRewardRequest`
        """
        model = UpsertRewardRequest()
        if include_optional:
            return UpsertRewardRequest(
                title = 'Gold Badge',
                description = 'Awarded for reaching Gold tier',
                badge_id = 'badge_gold',
                bonus_points = 500,
                metadata = None
            )
        else:
            return UpsertRewardRequest(
                title = 'Gold Badge',
                description = 'Awarded for reaching Gold tier',
        )
        """

    def testUpsertRewardRequest(self):
        """Test UpsertRewardRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
