# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_intent_request import PaymentIntentRequest

class TestPaymentIntentRequest(unittest.TestCase):
    """PaymentIntentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentIntentRequest:
        """Test PaymentIntentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentIntentRequest`
        """
        model = PaymentIntentRequest()
        if include_optional:
            return PaymentIntentRequest(
                course_id = '8e4fd4f8-d8f3-46b5-8786-6f7167a654f4',
                amount = 3999,
                currency = 'USD'
            )
        else:
            return PaymentIntentRequest(
                course_id = '8e4fd4f8-d8f3-46b5-8786-6f7167a654f4',
                amount = 3999,
                currency = 'USD',
        )
        """

    def testPaymentIntentRequest(self):
        """Test PaymentIntentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
