# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.start_migration_request import StartMigrationRequest

class TestStartMigrationRequest(unittest.TestCase):
    """StartMigrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartMigrationRequest:
        """Test StartMigrationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartMigrationRequest`
        """
        model = StartMigrationRequest()
        if include_optional:
            return StartMigrationRequest(
                source_shard_id = 'shard-00',
                target_shard_id = 'shard-01',
                entity_type = 'users',
                estimated_row_count = 50000,
                batch_size = 1000,
                dry_run = False
            )
        else:
            return StartMigrationRequest(
                source_shard_id = 'shard-00',
                target_shard_id = 'shard-01',
                entity_type = 'users',
                estimated_row_count = 50000,
                batch_size = 1000,
                dry_run = False,
        )
        """

    def testStartMigrationRequest(self):
        """Test StartMigrationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
