# coding: utf-8

"""
    TeachLink API

    TeachLink Backend API Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_login_post(self) -> None:
        """Test case for auth_login_post

        User login
        """
        pass

    def test_auth_register_post(self) -> None:
        """Test case for auth_register_post

        User registration
        """
        pass


if __name__ == '__main__':
    unittest.main()
