# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.course_request import CourseRequest

class TestCourseRequest(unittest.TestCase):
    """CourseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CourseRequest:
        """Test CourseRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CourseRequest`
        """
        model = CourseRequest()
        if include_optional:
            return CourseRequest(
                title = 'JavaScript Foundations',
                description = 'Learn modern JavaScript from first principles.',
                category = 'programming',
                level = 'beginner',
                price = 3999
            )
        else:
            return CourseRequest(
                title = 'JavaScript Foundations',
                description = 'Learn modern JavaScript from first principles.',
        )
        """

    def testCourseRequest(self):
        """Test CourseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
