# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.app_api import AppApi


class TestAppApi(unittest.TestCase):
    """AppApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppApi()

    def tearDown(self) -> None:
        pass

    def test_get_app_status(self) -> None:
        """Test case for get_app_status

        Get app status
        """
        pass


if __name__ == '__main__':
    unittest.main()
