# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.data_pipeline_api import DataPipelineApi


class TestDataPipelineApi(unittest.TestCase):
    """DataPipelineApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataPipelineApi()

    def tearDown(self) -> None:
        pass

    def test_run_etl(self) -> None:
        """Test case for run_etl

        Run an ETL job
        """
        pass


if __name__ == '__main__':
    unittest.main()
