# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchApi()

    def tearDown(self) -> None:
        pass

    def test_get_autocomplete(self) -> None:
        """Test case for get_autocomplete

        Get search autocomplete suggestions
        """
        pass

    def test_search_content(self) -> None:
        """Test case for search_content

        Search courses and learning content
        """
        pass


if __name__ == '__main__':
    unittest.main()
