# coding: utf-8

"""
    TeachLink API

    TeachLink Backend API Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_users_get(self) -> None:
        """Test case for users_get

        Get all users (Admin only)
        """
        pass

    def test_users_id_delete(self) -> None:
        """Test case for users_id_delete

        Delete user (Admin only)
        """
        pass

    def test_users_id_get(self) -> None:
        """Test case for users_id_get

        Get user by ID
        """
        pass

    def test_users_id_patch(self) -> None:
        """Test case for users_id_patch

        Update user
        """
        pass

    def test_users_post(self) -> None:
        """Test case for users_post

        Create a new user (Admin only)
        """
        pass


if __name__ == '__main__':
    unittest.main()
