# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.auto_rebalance_request import AutoRebalanceRequest

class TestAutoRebalanceRequest(unittest.TestCase):
    """AutoRebalanceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutoRebalanceRequest:
        """Test AutoRebalanceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutoRebalanceRequest`
        """
        model = AutoRebalanceRequest()
        if include_optional:
            return AutoRebalanceRequest(
                entity_types = ["users","courses"],
                auto_execute = False
            )
        else:
            return AutoRebalanceRequest(
                entity_types = ["users","courses"],
                auto_execute = False,
        )
        """

    def testAutoRebalanceRequest(self):
        """Test AutoRebalanceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
