# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.add_points_request import AddPointsRequest

class TestAddPointsRequest(unittest.TestCase):
    """AddPointsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddPointsRequest:
        """Test AddPointsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddPointsRequest`
        """
        model = AddPointsRequest()
        if include_optional:
            return AddPointsRequest(
                user_id = 'user_123',
                points = 100,
                activity_type = 'COURSE_COMPLETED'
            )
        else:
            return AddPointsRequest(
                user_id = 'user_123',
                points = 100,
                activity_type = 'COURSE_COMPLETED',
        )
        """

    def testAddPointsRequest(self):
        """Test AddPointsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
