# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.debugging_api import DebuggingApi


class TestDebuggingApi(unittest.TestCase):
    """DebuggingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DebuggingApi()

    def tearDown(self) -> None:
        pass

    def test_clear_captured_requests(self) -> None:
        """Test case for clear_captured_requests

        Clear the captured request buffer
        """
        pass

    def test_list_captured_requests(self) -> None:
        """Test case for list_captured_requests

        List recently captured requests
        """
        pass


if __name__ == '__main__':
    unittest.main()
