# coding: utf-8

"""
    TeachLink API

    TeachLink Backend API Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.courses_api import CoursesApi


class TestCoursesApi(unittest.TestCase):
    """CoursesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CoursesApi()

    def tearDown(self) -> None:
        pass

    def test_courses_get(self) -> None:
        """Test case for courses_get

        Get all courses
        """
        pass

    def test_courses_id_delete(self) -> None:
        """Test case for courses_id_delete

        Delete course
        """
        pass

    def test_courses_id_get(self) -> None:
        """Test case for courses_id_get

        Get course by ID
        """
        pass

    def test_courses_id_patch(self) -> None:
        """Test case for courses_id_patch

        Update course
        """
        pass

    def test_courses_post(self) -> None:
        """Test case for courses_post

        Create a new course
        """
        pass


if __name__ == '__main__':
    unittest.main()
