# coding: utf-8

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.gamification_api import GamificationApi


class TestGamificationApi(unittest.TestCase):
    """GamificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GamificationApi()

    def tearDown(self) -> None:
        pass

    def test_add_points(self) -> None:
        """Test case for add_points

        Add points to a user
        """
        pass

    def test_award_activity(self) -> None:
        """Test case for award_activity

        Award points for a user activity
        """
        pass

    def test_get_leaderboard(self) -> None:
        """Test case for get_leaderboard

        Get leaderboard
        """
        pass

    def test_get_user_progress(self) -> None:
        """Test case for get_user_progress

        Get user progress and points
        """
        pass

    def test_upsert_reward(self) -> None:
        """Test case for upsert_reward

        Create or update a tier reward
        """
        pass


if __name__ == '__main__':
    unittest.main()
