# coding: utf-8

"""
    TeachLink API

    TeachLink Backend API Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.health_api import HealthApi


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthApi()

    def tearDown(self) -> None:
        pass

    def test_health_get(self) -> None:
        """Test case for health_get

        Health check
        """
        pass

    def test_health_liveness_get(self) -> None:
        """Test case for health_liveness_get

        Liveness probe
        """
        pass


if __name__ == '__main__':
    unittest.main()
