export enum ErrorCode {
  AUTH_INVALID_CREDENTIALS = 'AUTH_001',
  AUTH_INVALID_TOKEN = 'AUTH_002',
  AUTH_FORBIDDEN = 'AUTH_003',
  AUTH_UNAUTHORIZED = 'AUTH_004',
  RESOURCE_NOT_FOUND = 'RES_001',
  RESOURCE_CONFLICT = 'RES_002',
  VALIDATION_ERROR = 'VAL_001',
  BUSINESS_RULE_VIOLATION = 'BUS_001',
  INTERNAL_SERVER_ERROR = 'SYS_001',
  SERVICE_UNAVAILABLE = 'SYS_002',
  RATE_LIMIT_EXCEEDED = 'SYS_003',
}
