# coding: utf-8

# flake8: noqa

"""
    TeachLink API

    TeachLink Backend API Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthApi",
    "CoursesApi",
    "HealthApi",
    "UsersApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AuthLoginPostRequest",
    "CoursesPostRequest",
    "UsersPostRequest",
]

# import apis into sdk package
from openapi_client.api.auth_api import AuthApi as AuthApi
from openapi_client.api.courses_api import CoursesApi as CoursesApi
from openapi_client.api.health_api import HealthApi as HealthApi
from openapi_client.api.users_api import UsersApi as UsersApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.auth_login_post_request import AuthLoginPostRequest as AuthLoginPostRequest
from openapi_client.models.courses_post_request import CoursesPostRequest as CoursesPostRequest
from openapi_client.models.users_post_request import UsersPostRequest as UsersPostRequest

