# coding: utf-8

# flake8: noqa

"""
    TeachLink API

    Automatically generated OpenAPI documentation for TeachLink backend APIs, including request and response examples.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AppApi",
    "AuthApi",
    "CoursesApi",
    "DataPipelineApi",
    "DebuggingApi",
    "GamificationApi",
    "PaymentsApi",
    "SearchApi",
    "ShardingApi",
    "UsersApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddPointsRequest",
    "ApiError",
    "ApiErrorErrorsInner",
    "ApiSuccess",
    "AutoRebalanceRequest",
    "AwardActivityRequest",
    "CourseRequest",
    "LoginRequest",
    "ManualRebalanceRequest",
    "PaymentIntentRequest",
    "RegisterRequest",
    "RouteShardRequest",
    "RunEtlRequest",
    "SearchResponse",
    "StartMigrationRequest",
    "UpsertRewardRequest",
]

# import apis into sdk package
from openapi_client.api.app_api import AppApi as AppApi
from openapi_client.api.auth_api import AuthApi as AuthApi
from openapi_client.api.courses_api import CoursesApi as CoursesApi
from openapi_client.api.data_pipeline_api import DataPipelineApi as DataPipelineApi
from openapi_client.api.debugging_api import DebuggingApi as DebuggingApi
from openapi_client.api.gamification_api import GamificationApi as GamificationApi
from openapi_client.api.payments_api import PaymentsApi as PaymentsApi
from openapi_client.api.search_api import SearchApi as SearchApi
from openapi_client.api.sharding_api import ShardingApi as ShardingApi
from openapi_client.api.users_api import UsersApi as UsersApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.add_points_request import AddPointsRequest as AddPointsRequest
from openapi_client.models.api_error import ApiError as ApiError
from openapi_client.models.api_error_errors_inner import ApiErrorErrorsInner as ApiErrorErrorsInner
from openapi_client.models.api_success import ApiSuccess as ApiSuccess
from openapi_client.models.auto_rebalance_request import AutoRebalanceRequest as AutoRebalanceRequest
from openapi_client.models.award_activity_request import AwardActivityRequest as AwardActivityRequest
from openapi_client.models.course_request import CourseRequest as CourseRequest
from openapi_client.models.login_request import LoginRequest as LoginRequest
from openapi_client.models.manual_rebalance_request import ManualRebalanceRequest as ManualRebalanceRequest
from openapi_client.models.payment_intent_request import PaymentIntentRequest as PaymentIntentRequest
from openapi_client.models.register_request import RegisterRequest as RegisterRequest
from openapi_client.models.route_shard_request import RouteShardRequest as RouteShardRequest
from openapi_client.models.run_etl_request import RunEtlRequest as RunEtlRequest
from openapi_client.models.search_response import SearchResponse as SearchResponse
from openapi_client.models.start_migration_request import StartMigrationRequest as StartMigrationRequest
from openapi_client.models.upsert_reward_request import UpsertRewardRequest as UpsertRewardRequest

