export enum AuditAction {
    // Authentication events
    LOGIN = 'LOGIN',
    LOGIN_FAILED = 'LOGIN_FAILED',
    LOGOUT = 'LOGOUT',
    REGISTER = 'REGISTER',
    PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
    PASSWORD_RESET = 'PASSWORD_RESET',
    PASSWORD_CHANGE = 'PASSWORD_CHANGE',
    EMAIL_VERIFIED = 'EMAIL_VERIFIED',
    TOKEN_REFRESH = 'TOKEN_REFRESH',
    SESSION_EXPIRED = 'SESSION_EXPIRED',
    SESSION_REVOKED = 'SESSION_REVOKED',
    // User management
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DELETED = 'USER_DELETED',
    USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
    USER_STATUS_CHANGED = 'USER_STATUS_CHANGED',
    // Data access
    DATA_VIEWED = 'DATA_VIEWED',
    DATA_CREATED = 'DATA_CREATED',
    DATA_UPDATED = 'DATA_UPDATED',
    DATA_DELETED = 'DATA_DELETED',
    DATA_EXPORTED = 'DATA_EXPORTED',
    DATA_IMPORTED = 'DATA_IMPORTED',
    // File operations
    FILE_UPLOADED = 'FILE_UPLOADED',
    FILE_DOWNLOADED = 'FILE_DOWNLOADED',
    FILE_DELETED = 'FILE_DELETED',
    FILE_SHARED = 'FILE_SHARED',
    // API access
    API_CALLED = 'API_CALLED',
    API_RATE_LIMITED = 'API_RATE_LIMITED',
    API_ERROR = 'API_ERROR',
    // Security events
    PERMISSION_DENIED = 'PERMISSION_DENIED',
    SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
    MFA_ENABLED = 'MFA_ENABLED',
    MFA_DISABLED = 'MFA_DISABLED',
    MFA_FAILED = 'MFA_FAILED',
    // Admin operations
    CONFIG_CHANGED = 'CONFIG_CHANGED',
    SETTING_UPDATED = 'SETTING_UPDATED',
    BACKUP_CREATED = 'BACKUP_CREATED',
    BACKUP_RESTORED = 'BACKUP_RESTORED',
    // Compliance
    DATA_RETENTION_APPLIED = 'DATA_RETENTION_APPLIED',
    AUDIT_LOG_EXPORTED = 'AUDIT_LOG_EXPORTED',
    REPORT_GENERATED = 'REPORT_GENERATED'
}
export enum AuditSeverity {
    INFO = 'INFO',
    WARNING = 'WARNING',
    ERROR = 'ERROR',
    CRITICAL = 'CRITICAL'
}
export enum AuditCategory {
    AUTHENTICATION = 'AUTHENTICATION',
    AUTHORIZATION = 'AUTHORIZATION',
    DATA_ACCESS = 'DATA_ACCESS',
    DATA_MODIFICATION = 'DATA_MODIFICATION',
    FILE_OPERATION = 'FILE_OPERATION',
    SYSTEM = 'SYSTEM',
    SECURITY = 'SECURITY',
    COMPLIANCE = 'COMPLIANCE'
}
