import { Injectable, Logger, BadRequestException } from '@nestjs/common';
import { ProviderFactoryService } from '../providers/provider-factory.service';
import { PaymentsService } from '../payments.service';
import { PaymentStatus } from '../entities/payment.entity';
import { WebhookQueueService } from './webhook-queue.service';
import { WebhookProvider } from './entities/webhook-retry.entity';
import {
  ISubscriptionWebhookEvent,
  IRefundWebhookData,
} from '../interfaces/payment-provider.interface';

interface IStripePaymentIntent {
  id: string;
  metadata: Record<string, unknown>;
}

interface IStripeCharge {
  payment_intent: string;
  refunds: {
    data: IRefundWebhookData[];
  };
}

interface IPayPalResource {
  id: string;
  parent_payment: string;
  amount: number;
}

interface IPayPalWebhookPayload {
  event_type: string;
  resource: IPayPalResource;
}

/**
 * Provides webhook operations.
 */
@Injectable()
export class WebhookService {
  private readonly logger = new Logger(WebhookService.name);

  constructor(
    private readonly paymentsService: PaymentsService,
    private readonly providerFactory: ProviderFactoryService,
    private readonly webhookQueueService: WebhookQueueService,
  ) {}

  /**
   * Handles stripe Webhook.
   * @param payload The payload to process.
   * @param signature The signature.
   * @returns The operation result.
   */
  async handleStripeWebhook(
    payload: Buffer | undefined,
    signature: string,
  ): Promise<{ received: boolean; webhookRetryId?: string }> {
    if (!payload) {
      this.logger.error('Missing raw body in Stripe webhook');
      return { received: false };
    }
    private async handlePaymentIntentSucceeded(paymentIntent: StripePaymentIntent): Promise<void> {
        // Update payment status to completed
        await this.paymentsService.updatePaymentStatus(paymentIntent.id, PaymentStatus.COMPLETED, paymentIntent.metadata);
    }
    private async handlePaymentIntentFailed(paymentIntent: StripePaymentIntent): Promise<void> {
        // Update payment status to failed
        await this.paymentsService.updatePaymentStatus(paymentIntent.id, PaymentStatus.FAILED, paymentIntent.metadata);
    }
  }

  private async handlePaymentIntentSucceeded(paymentIntent: IStripePaymentIntent): Promise<void> {
    // Update payment status to completed
    await this.paymentsService.updatePaymentStatus(
      paymentIntent.id,
      PaymentStatus.COMPLETED,
      paymentIntent.metadata,
    );
  }

  private async handlePaymentIntentFailed(paymentIntent: IStripePaymentIntent): Promise<void> {
    // Update payment status to failed
    await this.paymentsService.updatePaymentStatus(
      paymentIntent.id,
      PaymentStatus.FAILED,
      paymentIntent.metadata,
    );
  }

  private async handleChargeRefunded(charge: IStripeCharge): Promise<void> {
    // Process refund
    const refund = charge.refunds.data[0];
    await this.paymentsService.processRefundFromWebhook(charge.payment_intent, refund);
  }

  private async handleSubscriptionEvent(event: ISubscriptionWebhookEvent): Promise<void> {
    // Handle subscription events
    await this.paymentsService.handleSubscriptionEvent(event);
  }

  /**
   * Handles pay Pal Webhook.
   * @param payload The payload to process.
   * @param _transmissionId The transmission identifier.
   * @param _transmissionTime The transmission time.
   * @param _transmissionSig The transmission sig.
   * @param _certUrl The cert url.
   * @param _authAlgo The auth algo.
   * @returns The operation result.
   */
  async handlePayPalWebhook(
    payload: Record<string, unknown>,
    _transmissionId: string,
    _transmissionTime: string,
    _transmissionSig: string,
    _certUrl: string,
    _authAlgo: string,
  ): Promise<{ received: boolean; webhookRetryId?: string }> {
    const paypalPayload = payload as unknown as IPayPalWebhookPayload;

    try {
      // Queue the webhook for processing with retry logic
      const webhookRetryId = await this.webhookQueueService.queueWebhook({
        webhookRetryId: '', // Will be generated by the service
        provider: WebhookProvider.PAYPAL,
        payload,
        externalEventId: paypalPayload.event_type,
        headers: {
          'paypal-transmission-id': _transmissionId,
          'paypal-transmission-time': _transmissionTime,
          'paypal-transmission-sig': _transmissionSig,
          'paypal-cert-url': _certUrl,
          'paypal-auth-algo': _authAlgo,
        },
      });

      this.logger.log(`PayPal webhook queued for processing: ${webhookRetryId}`);
      return { received: true, webhookRetryId };
    } catch (error: any) {
      this.logger.error(`Failed to queue PayPal webhook: ${error.message}`);
      throw error;
    }
  }

  private async handlePayPalPaymentCompleted(resource: IPayPalResource): Promise<void> {
    // Update payment status to completed
    await this.paymentsService.updatePaymentStatus(resource.id, PaymentStatus.COMPLETED);
  }

  private async handlePayPalRefundCompleted(resource: IPayPalResource): Promise<void> {
    // Process refund
    await this.paymentsService.processRefundFromWebhook(resource.parent_payment, {
      id: resource.id,
      amount: resource.amount,
    });
  }
}
