import { Injectable, Logger, BadRequestException } from '@nestjs/common';
import { ProviderFactoryService } from '../providers/provider-factory.service';
import { PaymentsService } from '../payments.service';
import { PaymentStatus } from '../entities/payment.entity';
import { WebhookQueueService } from './webhook-queue.service';
import { WebhookProvider } from './entities/webhook-retry.entity';
import {
  SubscriptionWebhookEvent,
  RefundWebhookData,
} from '../interfaces/payment-provider.interface';

interface StripePaymentIntent {
  id: string;
  metadata: Record<string, unknown>;
}

interface StripeCharge {
  payment_intent: string;
  refunds: {
    data: RefundWebhookData[];
  };
}

interface PayPalResource {
  id: string;
  parent_payment: string;
  amount: number;
}

interface PayPalWebhookPayload {
  event_type: string;
  resource: PayPalResource;
}

@Injectable()
export class WebhookService {
  private readonly logger = new Logger(WebhookService.name);

  constructor(
    private readonly paymentsService: PaymentsService,
    private readonly providerFactory: ProviderFactoryService,
    private readonly webhookQueueService: WebhookQueueService,
  ) {}

  async handleStripeWebhook(
    payload: Buffer | undefined,
    signature: string,
  ): Promise<{ received: boolean; webhookRetryId?: string }> {
    if (!payload) {
      this.logger.error('Missing raw body in Stripe webhook');
      return { received: false };
    }

    let eventId: string;
    try {
      // Verify signature first before queuing
      const stripeProvider = this.providerFactory.getProvider('stripe');
      const event = await stripeProvider.handleWebhook(payload, signature);
      eventId = event.id;
    } catch (err: any) {
      this.logger.error(`Webhook signature verification failed: ${err.message}`);
      throw new BadRequestException('Webhook signature verification failed');
    }

    // Queue the webhook for processing with retry logic
    try {
      const webhookRetryId = await this.webhookQueueService.queueWebhook({
        webhookRetryId: '', // Will be generated by the service
        provider: WebhookProvider.STRIPE,
        payload,
        signature,
        externalEventId: eventId,
      });

      this.logger.log(`Stripe webhook queued for processing: ${webhookRetryId}`);
      return { received: true, webhookRetryId };
    } catch (error: any) {
      this.logger.error(`Failed to queue Stripe webhook: ${error.message}`);
      throw error;
    }
  }

  private async handlePaymentIntentSucceeded(paymentIntent: StripePaymentIntent): Promise<void> {
    // Update payment status to completed
    await this.paymentsService.updatePaymentStatus(
      paymentIntent.id,
      PaymentStatus.COMPLETED,
      paymentIntent.metadata,
    );
  }

  private async handlePaymentIntentFailed(paymentIntent: StripePaymentIntent): Promise<void> {
    // Update payment status to failed
    await this.paymentsService.updatePaymentStatus(
      paymentIntent.id,
      PaymentStatus.FAILED,
      paymentIntent.metadata,
    );
  }

  private async handleChargeRefunded(charge: StripeCharge): Promise<void> {
    // Process refund
    const refund = charge.refunds.data[0];
    await this.paymentsService.processRefundFromWebhook(charge.payment_intent, refund);
  }

  private async handleSubscriptionEvent(event: SubscriptionWebhookEvent): Promise<void> {
    // Handle subscription events
    await this.paymentsService.handleSubscriptionEvent(event);
  }

  async handlePayPalWebhook(
    payload: PayPalWebhookPayload,
    _transmissionId: string,
    _transmissionTime: string,
    _transmissionSig: string,
    _certUrl: string,
    _authAlgo: string,
  ): Promise<{ received: boolean; webhookRetryId?: string }> {
    try {
      // Queue the webhook for processing with retry logic
      const webhookRetryId = await this.webhookQueueService.queueWebhook({
        webhookRetryId: '', // Will be generated by the service
        provider: WebhookProvider.PAYPAL,
        payload,
        externalEventId: payload.event_type,
        headers: {
          'paypal-transmission-id': _transmissionId,
          'paypal-transmission-time': _transmissionTime,
          'paypal-transmission-sig': _transmissionSig,
          'paypal-cert-url': _certUrl,
          'paypal-auth-algo': _authAlgo,
        },
      });

      this.logger.log(`PayPal webhook queued for processing: ${webhookRetryId}`);
      return { received: true, webhookRetryId };
    } catch (error: any) {
      this.logger.error(`Failed to queue PayPal webhook: ${error.message}`);
      throw error;
    }
  }

  private async handlePayPalPaymentCompleted(resource: PayPalResource): Promise<void> {
    // Update payment status to completed
    await this.paymentsService.updatePaymentStatus(resource.id, PaymentStatus.COMPLETED);
  }

  private async handlePayPalRefundCompleted(resource: PayPalResource): Promise<void> {
    // Process refund
    await this.paymentsService.processRefundFromWebhook(resource.parent_payment, {
      id: resource.id,
      amount: resource.amount,
    });
  }
}
