apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teachlink-backend.fullname" . }}-secrets
  labels:
    {{- include "teachlink-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
