export const IDEMPOTENCY_REDIS_CLIENT = 'IDEMPOTENCY_REDIS_CLIENT';

export const IDEMPOTENCY_METADATA_KEY = 'idempotency:options';
export const IDEMPOTENCY_DEFAULT_HEADER_NAME = 'Idempotency-Key';
export const IDEMPOTENCY_DEFAULT_TTL_SECONDS = 86400;
export const IDEMPOTENCY_DEFAULT_LOCK_TTL_MS = 5000;
export const IDEMPOTENCY_DEFAULT_POLL_INTERVAL_MS = 50;
export const IDEMPOTENCY_DEFAULT_WAIT_TIMEOUT_MS = 5000;
