# coding: utf-8

# flake8: noqa
"""
    TeachLink API

    TeachLink Backend API Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.auth_login_post_request import AuthLoginPostRequest
from openapi_client.models.courses_post_request import CoursesPostRequest
from openapi_client.models.users_post_request import UsersPostRequest

